name: nic_decoder
description: A Flutter app to decode Sri Lankan NIC numbers.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

flutter:
  uses-material-design: true
  assets:
    - NIC_Decoder\nic_decoder\assets\sri_lanka_emblem.png

